# .cpanel.yml — place this file only in the main branch (or any branch you push code to)

deployment:
  enabled: true
  branch: deploy                          # cPanel will pull from this branch
  tasks:
    # Set deployment target
    - export DEPLOYPATH=/home3/jkuatca1/public_html

    # Completely wipe existing public_html content
    - /bin/rm -rf $DEPLOYPATH/* || true
    - /bin/rm -f $DEPLOYPATH/.* || true   # remove hidden files too (like .htaccess)

    # Copy everything from the deploy branch directly to public_html
    - /bin/cp -R $CPANEL_DEPLOYMENT_SOURCE/* $DEPLOYPATH/
    - /bin/cp -R $CPANEL_DEPLOYMENT_SOURCE/.* $DEPLOYPATH/ 2>/dev/null || true

    # Fix permissions
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;

    # React Router SPA fallback .htaccess (only if not already present in deploy branch)
    - |
      if [ ! -f $DEPLOYPATH/.htaccess ]; then
        /bin/echo "RewriteEngine On
      RewriteBase /
      RewriteCond %{REQUEST_FILENAME} -f [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^ - [L]
      RewriteRule ^ index.html [L]" > $DEPLOYPATH/.htaccess
      fi

# Optional: auto-build and update deploy branch when main receives a push
hooks:
  post-clone:
    - exec: |
        if [ "$CPANEL_GIT_BRANCH" = "main" ]; then
          echo "Detected push to main → rebuilding and updating deploy branch"
          cd frontend
          /usr/local/bin/npm ci --omit=dev
          /usr/local/bin/npm run build
          git checkout deploy 2>/dev/null || git checkout -b deploy
          git rm -rf . > /dev/null 2>&1 || true
          cp -r dist/* .
          cp dist/.htaccess . 2>/dev/null || true
          git add -A
          git commit -m "Auto-deploy build $(date +%Y-%m-%d_%H%M%S)" || echo "No changes"
          git push --force origin deploy
          echo "deploy branch updated and ready for deployment"
        fi